server:
  port: 8183

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/heroes_db
    username: felix

  flyway:
    url: jdbc:postgresql://localhost:5432/heroes_db
    schemas: public
    user: felix
    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always