spring:
  r2dbc:
    url: r2dbc:postgresql://db:5432/heroes_db
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://db:5432/heroes_db
    schemas: public
    user: postgres
    password: postgres