server:
  port: 8084

  datasource:
    url: jdbc:postgresql://localhost:5432/villains_db
    username: felix

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true