version: '3.9'
services:
  fight-service:
    build: .
    expose:
      - 8182
    ports:
      - "8182:8182"
    depends_on:
      - db-fight
    networks:
      - keycloak
      - backend
      - frontend
      - kafka
      - fight-internal
  db-fight:
    image: postgres:alpine
    networks:
      - fight-internal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db_container/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  kafka:
    external: true
  backend:
    external: true
  keycloak:
    external: true
  frontend:
    external: true

  fight-internal:
    driver: bridge