version: '3.9'
services:
  villain-service:
    build: .
    ports:
      - "8184:8184"
    depends_on:
      - db-villain
  db-villain:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db_container/init.sql:/docker-entrypoint-initdb.d/init.sql
