server:
  port: 8185

spring:
  kafka:
    bootstrap-servers: 0.0.0.0:8186
    consumer:
      bootstrap-servers:
        localhost:8186
      auto-offset-reset: earliest

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id:
              statistics
            authorization-grant-type:
              authorization_code
            scope:
              openid

        provider:
          keycloak:
            issuer-uri:
              http://localhost:8888/realms/super_realm
            user-name-attribute:
              preferred_username
      resourceserver:
        jwt:
          issuer-uri:
            http://localhost:8888/realms/super_realm

topics:
  winner_stats: winner_stats
  team_stats: team_stats
  fights: fights

groups:
  fight_winner_stats_group: fight_winner_stats_group
  fight_team_stats_group: fight_team_stats_group
  winner_stats_group: winner_stats_group
  team_stats_group: team_stats_group