server:
  port: 8185

spring:
  kafka:
    bootstrap-servers: 0.0.0.0:8186
    consumer:
      bootstrap-servers:
        localhost:8186
      auto-offset-reset: earliest

topics:
  winner_stats: winner_stats
  team_stats: team_stats
  fights: fights

groups:
  fight_winner_stats_group: fight_winner_stats_group
  fight_team_stats_group: fight_team_stats_group
  winner_stats_group: winner_stats_group
  team_stats_group: team_stats_group