server:
  port: 8182

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fights_db
    username: felix

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  kafka:
    bootstrap-servers:
      0.0.0.0:8186
    template:
      default-topic: fights

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://localhost:8888/realms/super_realm
#    resourceserver:
#      jwt:
#
#        issuer-uri :
#
#        key-uri: http://localhost:8888/auth/realms/super_realm/protocol/openid-connect/certs

hero_proxy_random:
  url: localhost:8183
  path: /api/heroes/random
villain_proxy_random:
  url: localhost:8184
  path: /api/villains/random

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always