server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fights_db
    username: felix

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true


  cloud:
    openfeign:
      circuitbreaker:
        enabled: true


  kafka:
    bootstrap-servers:
      localhost:9092
    template:
      default-topic: topics.fights

hero_proxy_random:
  url: localhost:8083
  path: /api/heroes/random
villain_proxy_random:
  url: localhost:8084
  path: /api/villains/random