services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "8183:8183"
    depends_on:
      - db
  db:
    image: postgres:alpine
    network_mode: "host"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres_container/init.sql:/docker-entrypoint-initdb.d/init.sql
