version: '3.9'
services:
  hero-service:
    build: .
    ports:
      - "8183:8183"
    depends_on:
      - db-hero
    networks:
      - backend
      - hero-internal
  db-hero:
    image: postgres:alpine
    networks:
      - hero-internal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db_container/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  backend:
    external: true

  hero-internal:
    driver: bridge